name: PaidMediaBuyerPro
options:
  bundleIdPrefix: com.mediabuyerpro
targets:
  PaidMediaBuyerPro:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - PaidMediaBuyerProApp.swift
      - ContentView.swift
      - Views
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mediabuyerpro.PaidMediaBuyerPro
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: WN3K69XEP4
        CODE_SIGN_STYLE: Automatic
