import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import { SiteFooter } from '@/components/SiteFooter';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for MediaBuyerPro.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#030712] text-slate-50">
      <main className="container mx-auto px-4 md:px-6 py-16 max-w-3xl">
        <Link
          href="/"
          className="group text-sm font-semibold text-slate-400 hover:text-white inline-flex items-center gap-2 transition-colors bg-white/5 px-4 py-2 rounded-full border border-white/5 hover:border-white/10 mb-10"
        >
          <ArrowLeft className="h-4 w-4 transition-transform group-hover:-translate-x-1" /> Back to home
        </Link>

        <h1 className="text-4xl md:text-5xl font-black tracking-tight mb-4">Terms of Service</h1>
        <p className="text-sm text-slate-500 font-medium mb-12">Last updated: July 2026</p>

        <div className="space-y-10 text-slate-300 leading-relaxed font-medium">
          <Section title="1. What you're buying">
            MediaBuyerPro is a one-time-purchase software tool that generates advertising strategy and
            creative content (hooks, scripts, ad copy, and launch plans) based on the information you
            provide. Your purchase grants you a personal, non-transferable license to use the generator
            and the content it produces for your own business or your clients&apos; businesses.
          </Section>
          <Section title="2. No performance guarantee">
            Advertising results depend on factors outside our control — your offer, budget, landing
            pages, market conditions, and execution. We do not guarantee any specific outcome, revenue,
            return on ad spend, or lead volume from using generated content.
          </Section>
          <Section title="3. Your responsibilities">
            You are responsible for reviewing all generated content before publishing it, and for
            ensuring your ads comply with the policies of the platforms you advertise on (Meta, Google,
            TikTok, etc.) and with applicable laws in your jurisdiction, including truth-in-advertising
            requirements.
          </Section>
          <Section title="4. AI-generated content">
            Content is generated by artificial intelligence and may occasionally contain inaccuracies.
            Treat outputs as expert-informed drafts, not professional advice. You own the outputs you
            generate, to the extent permitted by law.
          </Section>
          <Section title="5. Refunds">
            Because the product delivers its full value immediately upon generation, all sales are
            final once you have generated a Creative Pack. If you experience a technical problem that
            prevents you from using the product, contact us and we will make it right.
          </Section>
          <Section title="6. Payments">
            Payments are processed securely by Stripe. We never see or store your card details.
          </Section>
          <Section title="7. Changes">
            We may update these terms from time to time. Continued use of the product after changes
            constitutes acceptance of the updated terms.
          </Section>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xl font-black text-white mb-3">{title}</h2>
      <p className="text-slate-400">{children}</p>
    </section>
  );
}
